### PR TITLE
Matching Service Frontend

### PR DESCRIPTION
**Pull request by tim-pipi**
# Basic Frontend for Matching Service (Under 'Discuss' section)
image

## Idle View
if no topic / difficulty has been selected: 
image
else:
image

## Waiting View
image

## Match Found View
image

## Timeout View
image

## Error View
image

## Questions / Help Needed
* Is there other scenarios I forgot to consider?
* @Jnjy Is it possible to create APIs to query just the list of available **topics** in the question service? I hardcoded the list of topics at the moment. (same question for difficulty level - but I assume there is only 3 difficulty level)

### CODE REVIEW

**Comment by tim-pipi** [comment]
Hmmm, maybe we might need to make a view for if the user hasn't logged in yet - then this page will ask the user to make new account or sign in first? 

Not sure though if we need since its a nice to have right?

**Comment by Jnjy** [comment]
> @Jnjy Is it possible to create APIs to query just the list of available topics in the question service? I hardcoded the list of topics at the moment. (same question for difficulty level - but I assume there is only 3 difficulty level)

Yeap, that will be possible!

Update: Created a PR for the endpoint @tim-pipi

**Comment by Jnjy** [comment]
> Hmmm, maybe we might need to make a view for if the user hasn't logged in yet - then this page will ask the user to make new account or sign in first?
> 
> Not sure though if we need since its a nice to have right?

Valid concern, but I think for now we can try to get the matching service up first, then we can look into it

**Comment by zsh-eng** [comment]
LGTM

**Pull request merged**
